spring:
  application:
    name: fw-api-gateway

ribbon:
  ReadTimeout: 10000

zuul:
  routes:
    user:
      path: /api/user/**
      url: https://fw-auth-service.herokuapp.com/api/user
    auth:
      path: /api/login/**
      url: https://fw-auth-service.herokuapp.com/login
    influencer:
      path: /api/influencer/**
      url: https://fw-profile-service.herokuapp.com/api/influencer
    brand:
      path: /api/brand/**
      url: https://fw-profile-service.herokuapp.com/api/brand
    profile:
      path: /api/profile/**
      url: https://fw-profile-service.herokuapp.com/api/profile
    partnership:
      path: /api/partnership/**
      url: https://fw-partnership-service.herokuapp.com/api/partnership
    payment:
      path: /api/payment/**
      url: https://fw-payment-service.herokuapp.com/api/payment
    rating:
      path: /api/rating/**
      url: https://fw-rating-service.herokuapp.com/api/rating
    file:
      path: /api/file/**
      url: https://fw-file-service.herokuapp.com/api/file
    image:
      path: /api/image/**
      url: https://fw-file-service.herokuapp.com/api/image

  sensitiveHeaders: Cookie,Set-Cookie

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:8761}/eureka/
  instance:
    hostname: ${DOMAIN_NAME}
    secure-port-enabled: true
    non-secure-port-enabled: false
  password: ${USER_PASSWORD:password}

app:
  services:
    auth:
      url: https://fw-auth-service.herokuapp.com

server:
  error:
    include-message: always
