spring:
  application:
    name: fw-api-gateway

ribbon:
  ReadTimeout: 10000

zuul:
  routes:
    user:
      path: /api/user/**
      url: https://fw-auth-service.azurewebsites.net/api/user
    auth:
      path: /api/login/**
      url: https://fw-auth-service.azurewebsites.net/login
    influencer:
      path: /api/influencer/**
      url: https://fw-profile-service.azurewebsites.net/api/influencer
    brand:
      path: /api/brand/**
      url: https://fw-profile-service.azurewebsites.net/api/brand
    profile:
      path: /api/profile/**
      url: https://fw-profile-service.azurewebsites.net/api/profile
    partnership:
      path: /api/partnership/**
      url: https://fw-partnership-service.azurewebsites.net/api/partnership
    payment:
      path: /api/payment/**
      url: https://fw-payment-service.azurewebsites.net/api/payment
    rating:
      path: /api/rating/**
      url: https://fw-rating-service.azurewebsites.net/api/rating
    file:
      path: /api/file/**
      url: https://fw-file-service.azurewebsites.net/api/file
    image:
      path: /api/image/**
      url: https://fw-file-service.azurewebsites.net/api/image

  sensitiveHeaders: Cookie,Set-Cookie

eureka:
  client:
    serviceUrl:
      defaultZone: https://fw-discovery-server.azurewebsites.net/eureka
  instance:
    hostname: fw-api-gateway.azurewebsites.net
    secure-port-enabled: true
    non-secure-port-enabled: false
  password: ${USER_PASSWORD:password}

app:
  services:
    auth:
      url: https://fw-auth-service.azurewebsites.net

server:
  error:
    include-message: always
