spring:
  application:
    name: fw-api-gateway

ribbon:
  ReadTimeout: 10000

zuul:
  routes:
    user:
      path: /api/user/**
      url: https://fw-auth-service.herokuapp.com/api/user
    auth:
      path: /api/login/**
      url: https://fw-auth-service.herokuapp.com/login
    influencer:
      path: /api/influencer/**
      url: https://fw-profile-service.herokuapp.com/api/influencer
    brand:
      path: /api/brand/**
      url: https://fw-profile-service.herokuapp.com/api/brand
  sensitiveHeaders: Cookie,Set-Cookie

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:8761}/eureka/
  instance:
    hostname: ${DOMAIN_NAME}
    secure-port-enabled: true
    non-secure-port-enabled: false
  password: ${USER_PASSWORD:password}

app:
  services:
    auth:
      url: https://fw-auth-service.herokuapp.com
